Add ignore-not-found in checks of existence of gloo-resource-rollout job.

diff --git a/install/helm/gloo/templates/5-resource-rollout-check-job.yaml b/install/helm/gloo/templates/5-resource-rollout-check-job.yaml
--- a/install/helm/gloo/templates/5-resource-rollout-check-job.yaml
+++ b/install/helm/gloo/templates/5-resource-rollout-check-job.yaml
@@ -87,16 +87,21 @@ spec:
             if [ "$HAS_CUSTOM_RESOURCES" == "true" ]
             then
               # Wait for the resource rollout job to complete
-              kubectl -n {{ .Release.Namespace }} get job gloo-resource-rollout &> /dev/null
+              kubectl -n {{ .Release.Namespace }} get job --ignore-not-found gloo-resource-rollout &> /dev/null
               if [ $? -eq 0 ]
               then
                 # Exit immediately if the rollout job failed
-                kubectl -n {{ .Release.Namespace }} get job gloo-resource-rollout -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' | grep -i "True" &> /dev/null
+                kubectl -n {{ .Release.Namespace }} get job gloo-resource-rollout --ignore-not-found -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' | grep -i "True" &> /dev/null
                 if [ $? -eq 0 ]
                 then
                     echo "Rollout job failed. Not all resources were successfully created."
                     exit 1
                 fi
+                echo "Waiting for the resource rollout job to complete"
+                kubectl -n {{ .Release.Namespace }} wait --for=condition=complete job gloo-resource-rollout --timeout={{ .Values.gateway.rolloutJob.timeout }}s
+
+                # Clean up the rollout job up so it doesn't cause issues with upgrades
+                kubectl -n {{ .Release.Namespace }} delete job gloo-resource-rollout --ignore-not-found || exit $?
               fi
 
               # If the resource has been applied, re-applying it should output something like this
